### PR TITLE
Clippy run

### PR DESCRIPTION
**Pull request by leoyvens**
Fixed some clippy lints.

### CODE REVIEW

**Comment by ubnt-intrepid** [comment]
Thanks to send the PR.
If possible, would you be willing to add the configuration file of clippy?

**Comment by leoyvens** [comment]
I'll try to add clippy as an optional dependency.

**Comment by leoyvens** [comment]
I have added clippy as an optional dependency, to run it use `cargo build --features clippy`. I also added some clippy configurations. You may see the commit message for more details. Thanks for the suggestion of adding clippy!

I did not deal with some of the lints because they required a design decision and break public APIs.

**Comment by ubnt-intrepid** [comment]
Thanks!

**Pull request merged**
