### PR TITLE
Convenience operators for LinExpr and bug fix

### PR DESCRIPTION
**Pull request by leoyvens**
Some operations I found convenient while working with this lib. Also fixed a bug in `impl Sub<LinExpr> for f64`

### CODE REVIEW

**Comment by leoyvens** [comment]
@ubnt-intrepid Hello, did you get a chance to take a look at this?

**Comment by leoyvens** [comment]
@ubnt-intrepid friendly ping

**Comment by ubnt-intrepid** [comment]
@leodasvacas Thanks for the PR.  I am sorry I heard that the contact was delayed.

**Comment by leoyvens** [comment]
@ubnt-intrepid Thank you!

**Pull request merged**
